add grainy bg image
Waishnav/Watcher-website pull request #15
Opened 2022-10-15 22:16 UTC by steven4714

Added Grainy BG Image #5 
![Bildschirmfoto 2022-10-16 um 00 16 09](https://user-images.githubusercontent.com/46499853/196009591-628f3c80-5d9a-41b1-b75a-6a14a328829a.png)

2022-10-16 17:21 UTC, Waishnav requested changes

2022-10-16 17:21 UTC, Waishnav commented on src/index.css
> +  background-image: url('../src/assets/grainy-effect.png');
```background: rgb(0, 0, 0) url("../src/assets/grainy-effect.png");```

2022-10-16 17:21 UTC, Waishnav commented on src/index.css
> +  background-image: url('../src/assets/grainy-effect.png');
and delete background-color property

2022-10-17 06:59 UTC, steven4714 commented
Changed the color to 0,0,0 and deleted background-color property

![Bildschirmfoto 2022-10-17 um 08 58 02](https://user-images.githubusercontent.com/46499853/196109554-8ad9cd60-08a2-44ca-8d03-132eb1568351.png)

2022-10-17 09:43 UTC, Waishnav approved these changes

2022-10-17 09:44 UTC, merged